# Generated by Django 3.2.9 on 2022-10-09 11:15

from django.db import migrations, models
import todo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(default=todo_app.models.one_week_hence),
        ),
    ]
